// Material library. userData.uv = metres covered by one texture tile (world-space
// UVs are generated by the builder), userData.noShadow = don't cast shadows.
import * as THREE from 'three';

export function makeMaterials(T) {
  const M = {};
  const std = (o, uv, extra = {}) => { const m = new THREE.MeshStandardMaterial(o); m.userData.uv = uv; Object.assign(m.userData, extra); return m; };
  const phy = (o, uv, extra = {}) => { const m = new THREE.MeshPhysicalMaterial(o); m.userData.uv = uv; Object.assign(m.userData, extra); return m; };
  const nscale = (v) => new THREE.Vector2(v, v);

  // ---- architecture
  M.white = std({ color: 0xffffff, ...T.white, roughness: 0.95, metalness: 0.0, normalScale: nscale(0.6) }, 2.4);
  M.whiteClean = std({ color: 0xffffff, ...T.whiteClean, roughness: 0.8, metalness: 0.0, normalScale: nscale(0.4) }, 3.0);
  M.whiteSmooth = phy({ color: 0xeef1f4, roughness: 0.28, metalness: 0.0, clearcoat: 0.6, clearcoatRoughness: 0.2 }, null);
  M.metal = std({ color: 0xd7dce1, ...T.brushed, roughness: 0.9, metalness: 1.0 }, 1.2);
  M.chrome = std({ color: 0xe8ecef, roughness: 0.12, metalness: 1.0 }, null);
  M.dark = std({ color: 0xffffff, ...T.dark, roughness: 1.0, metalness: 0.55, normalScale: nscale(0.8) }, 2.4);
  M.darkSmooth = std({ color: 0x1c2026, roughness: 0.38, metalness: 0.6 }, null);
  M.gunmetal = std({ color: 0x3a4048, ...T.brushed, roughness: 0.8, metalness: 0.9 }, 1.5);
  M.hull = std({ color: 0x8b939b, ...T.dark, roughness: 1.0, metalness: 0.4 }, 4.0);
  M.hullPaint = std({ color: 0x40464d, ...T.white, roughness: 0.9, metalness: 0.3 }, 3.0);
  M.floor = std({ color: 0xffffff, ...T.floor, roughness: 1.0, metalness: 0.2, normalScale: nscale(0.5) }, 2.4);
  M.floorLight = std({ color: 0xffffff, ...T.floorLight, roughness: 0.9, metalness: 0.05, normalScale: nscale(0.5) }, 2.4);
  M.deck = std({ color: 0xffffff, ...T.deck, roughness: 1.0, metalness: 0.05, normalScale: nscale(0.7) }, 4.0);
  M.grating = std({ color: 0xffffff, ...T.grating, roughness: 0.55, metalness: 0.8 }, 1.0);
  M.hex = std({ color: 0xffffff, ...T.hex, roughness: 0.55, metalness: 0.05 }, 1.2);
  M.hazard = std({ color: 0xffffff, ...T.hazard, roughness: 0.6, metalness: 0.1 }, 0.8);
  M.rubber = std({ color: 0x131517, roughness: 0.85, metalness: 0.0 }, null);
  M.plastic = std({ color: 0x2a2f35, roughness: 0.45, metalness: 0.1 }, null);
  M.plasticWhite = std({ color: 0xdfe3e7, roughness: 0.35, metalness: 0.0 }, null);
  M.orange = std({ color: 0xffffff, ...T.fabric, roughness: 0.85, metalness: 0.0 }, 0.6);
  M.fabricGrey = std({ color: 0xffffff, ...T.fabricGrey, roughness: 0.9, metalness: 0.0 }, 0.6);
  M.orangeGloss = std({ color: 0xe0622a, roughness: 0.35, metalness: 0.0 }, null);
  M.yellow = std({ color: 0xe8b21a, roughness: 0.5, metalness: 0.2 }, null);
  M.redPaint = std({ color: 0xb8322a, roughness: 0.45, metalness: 0.2 }, null);
  M.screenOff = std({ color: 0x05070a, roughness: 0.1, metalness: 0.5 }, null);
  M.cable = std({ color: 0x15171a, roughness: 0.6, metalness: 0.2 }, null);
  M.copper = std({ color: 0xc27a4a, roughness: 0.35, metalness: 1.0 }, null);

  // ---- glass (no shadows, sorted transparent)
  M.glass = phy({ color: 0xbfe6f0, roughness: 0.04, metalness: 0.0, transparent: true, opacity: 0.16, depthWrite: false, envMapIntensity: 1.6, specularIntensity: 1.0, ior: 1.5 }, null, { noShadow: true });
  M.glassTint = phy({ color: 0x2a5566, roughness: 0.03, metalness: 0.25, transparent: true, opacity: 0.38, depthWrite: false, envMapIntensity: 1.8 }, null, { noShadow: true });
  M.glassFrost = phy({ color: 0xd8eef5, roughness: 0.5, metalness: 0.0, transparent: true, opacity: 0.55, depthWrite: false }, null, { noShadow: true });
  M.glassDome = phy({ color: 0xd6f2fa, roughness: 0.05, metalness: 0.1, transparent: true, opacity: 0.2, depthWrite: false, envMapIntensity: 2.0, side: THREE.DoubleSide }, null, { noShadow: true });
  M.glassFloor = phy({ color: 0x9fd3e0, roughness: 0.05, metalness: 0.1, transparent: true, opacity: 0.3, depthWrite: false, envMapIntensity: 1.5 }, null, { noShadow: true });

  // ---- emissives (bloom picks up anything brighter than ~1)
  const emi = (c, i, base = 0x050608) => std({ color: base, emissive: c, emissiveIntensity: i, roughness: 0.4, metalness: 0.0 }, null, { noShadow: true });
  M.cyan = emi(0x39f0ff, 9.0);
  M.cyanSoft = emi(0x39e6ff, 3.0);
  M.cyanDim = emi(0x2ad0ea, 1.2);
  M.teal = emi(0x2effc8, 8.0);
  M.light = emi(0xf2f8ff, 11.0, 0xffffff);
  M.lightWarm = emi(0xffe7c4, 10.0, 0xffffff);
  M.lightCool = emi(0xd8f0ff, 10.0, 0xffffff);
  M.orangeLight = emi(0xff7a2a, 8.0);
  M.red = emi(0xff2a24, 9.0);
  M.redDim = emi(0xff2a24, 2.0);
  M.amber = emi(0xffa726, 8.0);
  M.green = emi(0x44ff66, 8.0);
  M.blue = emi(0x3a8cff, 8.0);
  M.growLight = emi(0xff5cf0, 5.0);
  M.cryoFluid = std({ color: 0x0b3a58, emissive: 0x2ab8ff, emissiveIntensity: 1.3, roughness: 0.1, metalness: 0.0, transparent: true, opacity: 0.55, depthWrite: false }, null, { noShadow: true });
  M.greenFluid = std({ color: 0x0a3a14, emissive: 0x44ff88, emissiveIntensity: 1.1, roughness: 0.1, metalness: 0.0, transparent: true, opacity: 0.6, depthWrite: false }, null, { noShadow: true });

  // ---- nature
  M.bark = std({ color: 0xffffff, ...T.bark, roughness: 0.95, metalness: 0 }, 1.6, { keepUV: true });
  M.leaf = std({ color: 0xffffff, map: T.leaf.map, alphaTest: 0.45, side: THREE.DoubleSide, roughness: 0.75, metalness: 0 }, null);
  M.grass = std({ color: 0xffffff, map: T.grass.map, roughness: 0.95, metalness: 0 }, 1.5);
  M.soil = std({ color: 0xffffff, map: T.soil.map, roughness: 1.0, metalness: 0 }, 1.0);
  M.plant = std({ color: 0x3f8a3a, roughness: 0.7, metalness: 0 }, null);
  M.plantDark = std({ color: 0x2b6a33, roughness: 0.75, metalness: 0 }, null);
  M.plantLight = std({ color: 0x79b94a, roughness: 0.7, metalness: 0 }, null);
  M.creature = std({ color: 0xa9c7d6, emissive: 0x2a6f9a, emissiveIntensity: 0.6, roughness: 0.35, metalness: 0.0 }, null);

  // ---- additive fx
  const add = (c, o = 1, map = null) => new THREE.MeshBasicMaterial({ color: c, transparent: true, opacity: o, blending: THREE.AdditiveBlending, depthWrite: false, map, side: THREE.DoubleSide, fog: true });
  M.fxBeam = add(0xfff4e0, 0.07, T.beam); M.fxBeam.userData.noShadow = true;
  M.fxCyanBeam = add(0x44e8ff, 0.18, T.beam); M.fxCyanBeam.userData.noShadow = true;
  M.fxBlueBeam = add(0x3aa0ff, 0.12, T.beam); M.fxBlueBeam.userData.noShadow = true;
  M.fxHolo = add(0x55eeff, 0.35); M.fxHolo.userData.noShadow = true;

  for (const k in M) M[k].name = k;
  return M;
}
